### ISSUE TITLE
Failed to load a language-mscript package grammar

### ISSUE THREAD

**Issue by itstake** [jacobwgillespie/language-mscript#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.1
**Thrown From**: [language-mscript](https://github.com/jacobwgillespie/language-mscript) package, v0.2.1

### Stack Trace

Failed to load a language-mscript package grammar

```
At Grammar missing required scopeName property: /Users/itstake/.atom/packages/language-mscript/grammars/mscript.cson in /Users/itstake/.atom/packages/language-mscript/grammars/mscript.cson

Error: Grammar missing required scopeName property: /Users/itstake/.atom/packages/language-mscript/grammars/mscript.cson
  at /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:115:64
  at /Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:181:59
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

  at /Users/itstake/.atom/packages/language-mscript/grammars/mscript.cson:1:1
```

### Commands

```
     -0:15.1 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
language-mscript, v0.2.1

# Dev
No dev packages
```

**Comment by jacobwgillespie** [comment]
Thanks for the report - fixed in 7a81a8231a45fff01eed44143048d93ef0b7e845 (0.2.2)

:tada:
